package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 7 mars 2017 kl 16:38 CET
*/

public interface ChatOperations 
{
  String say (ChatApp.ChatCallback objref, String message);

  // session). this should make a client active.
  int join (ChatApp.ChatCallback objref, String usrname);

  // list should give you a list of all active users.
  String list (ChatApp.ChatCallback objref);
} // interface ChatOperations
