package ChatApp;


/**
* ChatApp/ChatCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 7 mars 2017 kl 16:38 CET
*/

public interface ChatCallback extends ChatCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatCallback
